### PR TITLE
Add ability to edit code by hand

### LINKED ISSUE #144: when in "code mode" should be able to edit the code by hand.
this would be for easily adding children 
and adding props not supported in the editor

i could look at adding a PR

### PR DESCRIPTION
**Pull request by johnletey**
**NOTE:** Still need to handle the case if you input invalid code.

Closes #144.

### CODE REVIEW

**Comment by johno** [comment]
Looking good so far! Agreed, we should display an error in the editor when the code is invalid (likely debounced so we don't display it while they're typing). We should probably also make the editor monospace.

**Comment by Caryyon** [comment]
Maybe we could utilize draft.js and some emotion styling to make it work more like an IDE?

**Comment by souporserious** [comment]
Not sure if it's overkill, but could be nice to utilize [monaco-editor](https://www.npmjs.com/package/@monaco-editor/react).

**Comment by johno** [comment]
Yeah, I'd love to see monaco-editor go in for the code editing experience. I'll go ahead and merge this though since it at least makes editing possible. I'll open up a new issue for monaco.

Thanks for the PR @johnletey!

**Pull request merged**
