### PR TITLE
feat: Don't unselect when deleting element

### LINKED ISSUE #71: When deleting a component, everything is unselected
When deleting components off the page, the selection state is completely lost. Something should stay selected, ideally something within the same group as a similar position in the tree.

delete

### PR DESCRIPTION
**Pull request by johnletey**
This PR makes sure that when deleting components, the selection state is maintained.

I have marked this as a draft PR, as when trying to delete an entire block (instead of just a component), the UI crashes. This is the same behaviour to what was described in https://github.com/blocks/blocks/issues/59#issuecomment-558517858.

Closes #71

### CODE REVIEW

**Comment by johno** [comment]
The UI crashes only when empty, right?

**Comment by johnletey** [comment]
This is the case for when the editor is empty, but I've also introduced this error here as well 😬

For some reason, when calling `setElementId` on the `Blocks.Root` component, the UI crashes.

**Comment by johno** [comment]
Gotcha, yeah we shouldn't really ever call it at Blocks.Root (and probably hide the parent navigation button when the parent is the root).

**Comment by johnletey** [comment]
Agree!

I have not found any logical way of working around this: checking to see if the parent to the current component is the `Blocks.Root` component. Have any ideas @johno?

**Comment by johno** [comment]
I guess we never want to add a UUID to Blocks.Root when it comes down to it 🤔

**Comment by johno** [comment]
Partially addressed in #83

**Comment by johnletey** [comment]
Appreciate the help @johno 😄

I can confirm that your changes fix the bug that I introduced with this change. Your changes will also make it a lot easier to address #59, which I will start working on now.

**Comment by johno** [comment]
Amazing, thanks @johnletey!

**Pull request merged**
