### PR TITLE
Add viewports preview view 📱💻 🖥

### LINKED ISSUE #53: Add mobile + tablet views to the canvas
We could potentially add zoom support as well.

### PR DESCRIPTION
**Pull request by souporserious**
blocks-viewport-progress

Goals for this first pass:

- [x] Disable DND in viewports mode
- [x] Performance (maybe disabling DND will fix this)
- [x] Auto-adjust iframe height (maybe it's fine to leave for now)
- [x] Read from ThemeUI breakpoints
- [x] Scroll syncing (I have this in a Codesandbox, probably better in a future PR)

closes #53

### CODE REVIEW

**Comment by johno** [comment]
This is looking amazing! I'm definitely all for stripping things out to ship earlier than later (iframe height and scroll syncing).

**Comment by souporserious** [comment]
@johno thanks! 🤗 Sounds good! I'll do a pass on the perf stuff and see if I can get anywhere and move the rest into a follow up issue.

**Comment by souporserious** [comment]
@johno this should be ready for review if you want to take a peek 👀. Still a lot to do and there's some rendering wonkiness, but DND is at least disabled which made performance slightly better and prevents any errors. I think we'll need to eventually move away from `react-frame-component` to have finer control over how iframes render.

**Comment by johnletey** [comment]
@souporserious Was looking at the latest deployment, and it looks like the iframes break in Safari.

**Comment by souporserious** [comment]
Whoops 😅 didn't do any cross-browser testing. It looks related to an issue I had earlier when directly rendering the viewports view on load, for some reason it wouldn't load the styles into the iframe properly which looks like what's happening here. I'll check it out!

**Pull request merged**
